---
title: "temp1"
output: html_document
---
Beginning of Set Up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(anomalize)
library(tidyverse)
library(tibbletime)
library(stringr)
library(lubridate)
```

```{r}
anomaly_data <- read.csv("Anomaly_Data.csv")

anomaly_data$DC_QTY <- as.numeric(as.character(anomaly_data$DC_QTY))
```

```{r}
anomaly_data$TRANSACTION_DATE = str_replace_all(anomaly_data$TRANSACTION_DATE,pattern = "MAR",replacement="03")
anomaly_data$TRANSACTION_DATE = str_replace_all(anomaly_data$TRANSACTION_DATE,pattern = "APR",replacement="04")
anomaly_data$TRANSACTION_DATE = str_replace_all(anomaly_data$TRANSACTION_DATE,pattern = "MAY",replacement="05")
anomaly_data$TRANSACTION_DATE = str_replace_all(anomaly_data$TRANSACTION_DATE,pattern = "JUN",replacement="06")

anomaly_data$TRANSACTION_DATE = str_replace_all(anomaly_data$TRANSACTION_DATE,pattern = "JUL",replacement="07")
anomaly_data$TRANSACTION_DATE = str_replace_all(anomaly_data$TRANSACTION_DATE,pattern = "AUG",replacement="08")
anomaly_data$TRANSACTION_DATE = str_replace_all(anomaly_data$TRANSACTION_DATE,pattern = "SEP",replacement="09")
anomaly_data$TRANSACTION_DATE = str_replace_all(anomaly_data$TRANSACTION_DATE,pattern = "OCT",replacement="10")

anomaly_data$TRANSACTION_DATE = str_replace_all(anomaly_data$TRANSACTION_DATE,pattern = "NOV",replacement="11")
anomaly_data$TRANSACTION_DATE = str_replace_all(anomaly_data$TRANSACTION_DATE,pattern = "DEC",replacement="12")
anomaly_data$TRANSACTION_DATE = str_replace_all(anomaly_data$TRANSACTION_DATE,pattern = "JAN",replacement="01")
anomaly_data$TRANSACTION_DATE = str_replace_all(anomaly_data$TRANSACTION_DATE,pattern = "FEB",replacement="02")
```

```{r}
anomaly_data$TRANSACTION_DATE = dmy(anomaly_data$TRANSACTION_DATE)
anomaly_data <- anomaly_data %>% arrange(TRANSACTION_DATE)
```

End of Set Up

```{r}
cleaner_data <- anomaly_data %>% 
  filter(DELIVERED_QUANTITY>0&DC_QTY>0)%>%
  mutate(unit_price_discrepancy = abs((DELIVERED_PRICE/DELIVERED_QUANTITY)-UNIT_PRICE))

```

```{r}
#GRAPH
qty_price_anomalies <- cleaner_data %>%
    filter(unit_price_discrepancy>1|DC_QTY!=DELIVERED_QUANTITY)

qty_price_anomalies%>%select(DELIVERED_QUANTITY,DELIVERED_PRICE,unit_price_discrepancy)%>%summary()


qty_price_anomalies%>%filter(DELIVERED_QUANTITY<3)%>%ggplot(aes(x=DELIVERED_QUANTITY))+
geom_bar(fill="#34b554")
qty_price_anomalies%>%ggplot(aes(y =DELIVERED_PRICE))+geom_boxplot(fill="#34b554")
```

```{r}

return_issues <- anomaly_data %>% 
    filter(DELIVERED_QUANTITY<=0 | DC_QTY <= 0)

```

```{r}
zero_data <- return_issues %>%
    filter(DELIVERED_QUANTITY==0|DC_QTY == 0)


```

```{r}
#GRAPH

#no refunds
zero_DC <-zero_data %>%
    filter(DC_QTY>0 & DELIVERED_PRICE/DC_QTY!=UNIT_PRICE*-1)

zero_DC%>%select(DC_QTY,DELIVERED_PRICE)%>%summary()

zero_DC%>%ggplot(aes(x=DC_QTY))+geom_bar(fill="#34b554")
zero_DC%>%ggplot(aes(y =DELIVERED_PRICE))+geom_boxplot(fill="#34b554")


```
```{r}
zero_delivered <- zero_data %>%
    filter(DELIVERED_QUANTITY>0 )

zero_delivered%>%select(DELIVERED_QUANTITY,DELIVERED_PRICE)%>%summary()


zero_delivered%>%ggplot(aes(x=DELIVERED_QUANTITY))+geom_bar(fill="#34b554")
zero_delivered%>%ggplot(aes(y =DELIVERED_PRICE))+geom_boxplot(fill="#34b554")
zero_delivered%>%filter(DELIVERED_PRICE<300)%>%ggplot(aes(y =DELIVERED_PRICE))+geom_boxplot(fill="#34b554")
```



```{r}
#GRAPH
other_return_issues <- return_issues %>%
    filter(DELIVERED_QUANTITY<0 | DC_QTY<0)%>%
    filter(abs((DELIVERED_PRICE/DELIVERED_QUANTITY)-UNIT_PRICE)>0.05)

other_return_issues%>%select(DELIVERED_QUANTITY,DC_QTY,DELIVERED_PRICE)%>%summary()

other_return_issues%>%ggplot(aes(x=DELIVERED_QUANTITY))+geom_bar(fill="#34b554")
other_return_issues%>%filter(DELIVERED_QUANTITY>-50)%>%ggplot(aes(x=DELIVERED_QUANTITY))+geom_bar(fill="#34b554")
other_return_issues%>%ggplot(aes(y=DELIVERED_PRICE))+geom_boxplot(fill="#34b554")
other_return_issues%>%filter(DELIVERED_PRICE<300)%>%ggplot(aes(y=DELIVERED_PRICE))+geom_boxplot(fill="#34b554")
```

End of General Anomalies

Start of Time Series

```{r}
 tsd <- cleaner_data %>%
    filter(unit_price_discrepancy<=1&DC_QTY==DELIVERED_QUANTITY)%>%
    mutate(month = month(TRANSACTION_DATE)) %>%
    filter(ACCOUNT_NAME=="BRINKER-CHILI'S #075")%>%
    filter(ORGANIZATION.NUMBER=="FRESHPOINT_158")%>%
    filter(DC_PROD_NUM  == 101217)

#not just delivered price, but also other numerical variables
tsd <- data.frame(tsd$TRANSACTION_DATE,tsd$DELIVERED_PRICE)
tsd_tbl_time <- as_tbl_time(tsd, tsd.TRANSACTION_DATE)

```


```{r}


# Time Frequency
#> frequency = 26 weeks
#> [1] 7
# Time Trend

#> trend = 94 weeks
#> [1] 91

tsd_tbl_time%>%
    time_decompose(tsd.DELIVERED_PRICE, method = "STL",frequency = "auto",trend = "auto") %>%
    anomalize(remainder, method = "iqr",alpha = 0.025) %>%
    time_recompose() %>%
    # Anomaly Visualization
    plot_anomalies(time_recomposed = TRUE, ncol = 3, alpha_dots = 0.25, color_no = "#0c5e2b", color_yes = "#e86e22", fill_ribbon = "#a4c1ad") +
    labs(title = "ITRADE Anomaly Detection", subtitle = "BRINKER-CHILI'S #075, FRESHPOINT_158, 101217/SpringMix", x= "Transaction Date", 
         y = "Delivered Price")


```